<?php
/**
 * WHISKER — Database Configuration
 * Generated by the installer. Edit manually if needed.
 */

return [
    'host'    => 'localhost',
    'port'    => 3306,
    'name'    => 'whisker_cart',
    'user'    => 'root',
    'pass'    => '',
    'charset' => 'utf8mb4',
    'prefix'  => 'wk_',
];
